INSERT INTO `flight_management_system`.`airports` (`airport_code`, `airport_location`, `airport_name`)
VALUES
("AMD", "Ahmedabad, Gujarat", "Ahmedabad Airport"),
("DEL", "Delhi", "Indira Gandhi International Airport"),
("BOM", "Mumbai, Maharashtra", "Chhatrapati Shivaji Maharaj International Airport"),
("BLR", "Bengaluru, Karnataka", "Kempegowda International Airport"),
("MAA", "Chennai, Tamil Nadu", "Chennai International Airport"),
("HYD", "Hyderabad, Telangana", "Rajiv Gandhi International Airport"),
("CCU", "Kolkata, West Bengal", "Netaji Subhas Chandra Bose International Airport"),
("PNQ", "Pune, Maharashtra", "Pune Airport"),
("GOI", "Goa", "Goa International Airport"),
("COK", "Kochi, Kerala", "Cochin International Airport"),
("TRV", "Thiruvananthapuram, Kerala", "Trivandrum International Airport"),
("IXC", "Chandigarh", "Chandigarh Airport"),
("JAI", "Jaipur, Rajasthan", "Jaipur International Airport"),
("LKO", "Lucknow, Uttar Pradesh", "Chaudhary Charan Singh International Airport"),
("ATQ", "Amritsar, Punjab", "Sri Guru Ram Dass Jee International Airport"),
("SXR", "Srinagar, Jammu and Kashmir", "Sheikh ul-Alam International Airport"),
("IXB", "Bagdogra, West Bengal", "Bagdogra Airport"),
("VNS", "Varanasi, Uttar Pradesh", "Lal Bahadur Shastri International Airport"),
("PAT", "Patna, Bihar", "Jay Prakash Narayan International Airport"),
("GAY", "Gaya, Bihar", "Gaya Airport");
